# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='algo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nalgo.proto\":\n\x12SingleModalRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x16\n\x0esingleParamter\x18\x02 \x01(\t\"1\n\x13SingleModalResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"8\n\x11MultiModalRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x15\n\rmultiParamter\x18\x02 \x01(\t\"0\n\x12MultiModalResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\x90\x01\n\x0b\x41lgoService\x12\x41\n\x12getSingleModalData\x12\x13.SingleModalRequest\x1a\x14.SingleModalResponse\"\x00\x12>\n\x11getMultiModalData\x12\x12.MultiModalRequest\x1a\x13.MultiModalResponse\"\x00\x62\x06proto3'
)




_SINGLEMODALREQUEST = _descriptor.Descriptor(
  name='SingleModalRequest',
  full_name='SingleModalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SingleModalRequest.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='singleParamter', full_name='SingleModalRequest.singleParamter', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=72,
)


_SINGLEMODALRESPONSE = _descriptor.Descriptor(
  name='SingleModalResponse',
  full_name='SingleModalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SingleModalResponse.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SingleModalResponse.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=123,
)


_MULTIMODALREQUEST = _descriptor.Descriptor(
  name='MultiModalRequest',
  full_name='MultiModalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MultiModalRequest.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiParamter', full_name='MultiModalRequest.multiParamter', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=181,
)


_MULTIMODALRESPONSE = _descriptor.Descriptor(
  name='MultiModalResponse',
  full_name='MultiModalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MultiModalResponse.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='MultiModalResponse.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=231,
)

DESCRIPTOR.message_types_by_name['SingleModalRequest'] = _SINGLEMODALREQUEST
DESCRIPTOR.message_types_by_name['SingleModalResponse'] = _SINGLEMODALRESPONSE
DESCRIPTOR.message_types_by_name['MultiModalRequest'] = _MULTIMODALREQUEST
DESCRIPTOR.message_types_by_name['MultiModalResponse'] = _MULTIMODALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SingleModalRequest = _reflection.GeneratedProtocolMessageType('SingleModalRequest', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEMODALREQUEST,
  '__module__' : 'algo_pb2'
  # @@protoc_insertion_point(class_scope:SingleModalRequest)
  })
_sym_db.RegisterMessage(SingleModalRequest)

SingleModalResponse = _reflection.GeneratedProtocolMessageType('SingleModalResponse', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEMODALRESPONSE,
  '__module__' : 'algo_pb2'
  # @@protoc_insertion_point(class_scope:SingleModalResponse)
  })
_sym_db.RegisterMessage(SingleModalResponse)

MultiModalRequest = _reflection.GeneratedProtocolMessageType('MultiModalRequest', (_message.Message,), {
  'DESCRIPTOR' : _MULTIMODALREQUEST,
  '__module__' : 'algo_pb2'
  # @@protoc_insertion_point(class_scope:MultiModalRequest)
  })
_sym_db.RegisterMessage(MultiModalRequest)

MultiModalResponse = _reflection.GeneratedProtocolMessageType('MultiModalResponse', (_message.Message,), {
  'DESCRIPTOR' : _MULTIMODALRESPONSE,
  '__module__' : 'algo_pb2'
  # @@protoc_insertion_point(class_scope:MultiModalResponse)
  })
_sym_db.RegisterMessage(MultiModalResponse)



_ALGOSERVICE = _descriptor.ServiceDescriptor(
  name='AlgoService',
  full_name='AlgoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=234,
  serialized_end=378,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSingleModalData',
    full_name='AlgoService.getSingleModalData',
    index=0,
    containing_service=None,
    input_type=_SINGLEMODALREQUEST,
    output_type=_SINGLEMODALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getMultiModalData',
    full_name='AlgoService.getMultiModalData',
    index=1,
    containing_service=None,
    input_type=_MULTIMODALREQUEST,
    output_type=_MULTIMODALRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALGOSERVICE)

DESCRIPTOR.services_by_name['AlgoService'] = _ALGOSERVICE

# @@protoc_insertion_point(module_scope)
