# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import algo_pb2 as algo__pb2


class AlgoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getSingleModalData = channel.unary_unary(
        '/AlgoService/getSingleModalData',
        request_serializer=algo__pb2.SingleModalRequest.SerializeToString,
        response_deserializer=algo__pb2.SingleModalResponse.FromString,
        )
    self.getMultiModalData = channel.unary_unary(
        '/AlgoService/getMultiModalData',
        request_serializer=algo__pb2.MultiModalRequest.SerializeToString,
        response_deserializer=algo__pb2.MultiModalResponse.FromString,
        )


class AlgoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getSingleModalData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMultiModalData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AlgoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getSingleModalData': grpc.unary_unary_rpc_method_handler(
          servicer.getSingleModalData,
          request_deserializer=algo__pb2.SingleModalRequest.FromString,
          response_serializer=algo__pb2.SingleModalResponse.SerializeToString,
      ),
      'getMultiModalData': grpc.unary_unary_rpc_method_handler(
          servicer.getMultiModalData,
          request_deserializer=algo__pb2.MultiModalRequest.FromString,
          response_serializer=algo__pb2.MultiModalResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AlgoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
